---
version: '3.2'
services:
  api:
    image: ${APP_NAME}/api:latest
    container_name: api
    env_file:
      - "${API_ENV_PATH}"
    network_mode: host
  front:
    image: ${APP_NAME}/front:latest
    container_name: front
    env_file:
      - "${FRONT_ENV_PATH}"
    network_mode: host
  nginx:
    image: ${APP_NAME}/nginx:latest
    container_name: nginx
    depends_on:
      - api
      - front
    network_mode: host
