---
version: '3.2'
services:
  api:
    image: ${APP_NAME}/api:latest
    container_name: api
    volumes:
      - type: bind
        source: "${API_DIR}"
        target: "/opt/app"
    command: /usr/local/bin/entrypoint.sh --debug
    env_file:
      - "${API_ENV_PATH}"
    network_mode: host
  front:
    image: ${APP_NAME}/front:latest
    container_name: front
    volumes:
      - type: bind
        source: "${FRONT_DIR}"
        target: "/opt/app"
    working_dir: /opt/app
    command: /usr/local/bin/entrypoint.sh --debug
    network_mode: host
  nginx:
    image: ${APP_NAME}/nginx:latest
    container_name: nginx
    depends_on:
      - api
      - front
    network_mode: host
